### ISSUE TITLE
Would love to be on that list

### ISSUE THREAD

**Issue by mateitudor** [j9t/vegan-web-developers#1]
Hi, My name is Tudor Matei, I'm a vegan, nonbinary front-end developer and UI/UX designer. My passions are intersectional activism, animal and human rights, design & coding.

You can find me here:
https://mateitudor.com
https://mastodon.social/@mateitudor
https://dribbble.com/mateitudor

Thank you in advance and would love to work on projects with other vegan devs & designers.

**Comment by j9t** [comment]
Hi @mateitudor—awesome, welcome aboard!

Added you with [ec3fb607](https://gitlab.com/j9t/vegan-web-developers/-/commit/ec3fb60720622b73b3fe1281583a3aff3b788d14)!
