### ISSUE TITLE
Alejandro Marrero

### ISSUE THREAD

**Issue by alejanfm** [j9t/vegan-web-developers#2]
* Your full name: Alejandro Marrero
* Your website: https://afm.dev
* Your Mastodon or Twitter account: https://twitter.com/afmdev

**Comment by j9t** [comment]
Cool! [Added](https://gitlab.com/j9t/vegan-web-developers/-/commit/80ec84611a5e326ad3ebccb916e59d747f394d41), and [update is live](https://j9t.gitlab.io/vegan-web-developers/)!
